name: Build and Publish

on:
  push:
    tags:
      - v*

jobs:
    call-build:
        uses: ./.github/workflows/build.yml
    
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: pru_ledpwm
            
            - name: Publish
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                tag: ${{ github.ref_name }}
              run: |
                gh release create "$tag" pru_ledpwm.* \
                    --repo="$GITHUB_REPOSITORY" \
                    --generate-notes
